view:
  site:
    needLoginArticleReadCount: 30
    zsxqArticleReadCount: 20
    websiteName: 技术派
    websiteLogoUrl:
    websiteFaviconIconUrl:
    zsxqUrl: ''
    zsxqPosterUrl: ''
    contactMeTitle: 欢迎关注微信公众号

    # 改成本地图片
    contactMeWxQrCode: D:\DESKTOP\Storage\image\wx_qrcode.jpg
    contactMeStarQrCode: http://127.0.0.1:8080/image/qrcode_star.jpg

    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案号:还在搞哈哈哈哈哈
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到技术派 ~~
    oss:
