view:
  site:
    needLoginArticleReadCount: 30
    zsxqArticleReadCount: 20
    websiteName: CodingNinja
    websiteLogoUrl:
    websiteFaviconIconUrl:
    zsxqUrl: ''
    zsxqPosterUrl: ''
    contactMeTitle: 欢迎关注微信公众号
    contactMeWxQrCode:
    contactMeStarQrCode:
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案号:还在搞哈哈哈哈哈
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://codingninja555.xyz
    welcomeInfo: Welcome!!!
    oss:
