image:
  abs-tmp-path: D:/DESKTOP/Storage
  web-img-path: /image/
  tmp-upload-path: D:/DESKTOP/Storage
  cdn-host:
  oss:
    type: ali
    prefix: 
    endpoint: 
    ak: 
    sk: 
    bucket: 
    host: 


spring:
  web:
    resources:
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${image.abs-tmp-path}
        - file:${image.abs-tmp-path}
